name: Check Spelling
on: [push, pull_request]
permissions:
  contents: write
  pull-requests: write

jobs:  
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Check Spelling
        uses: check-spelling/check-spelling@v0.0.22
