name: Update Releases JSON
permissions:
  contents: write

on:
  release:
    types: [published, prereleased]

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest releases (including prereleases)
        id: releases
        run: |
            curl -s https://api.github.com/repos/${{ github.repository }}/releases?per_page=100 \
            | jq '{
                latest: (map(select(.prerelease == false))[0] | {tag_name, asset_url: (if .assets|length>0 then .assets[0].browser_download_url else null end)}),
                prerelease: (map(select(.prerelease == true))[0] | {tag_name, asset_url: (if .assets|length>0 then .assets[0].browser_download_url else null end)})
              }' > releases.json

      - name: Commit to gh-pages
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git fetch origin gh-pages || true
          git checkout gh-pages || git checkout --orphan gh-pages
          mv releases.json ./releases.json
          git add releases.json
          git commit -m "Update releases JSON [skip ci]" || echo "No changes to commit"
          git push origin gh-pages
